const mongoose = require("mongoose");

const reportSchema = new mongoose.Schema(
  {
    // ============================================================
    // REPORT TYPE
    // ============================================================

    reportType: {
      type: String,
      enum: ["SALES", "CUSTOMERS"],
      required: true,
      index: true,
    },

    // ============================================================
    // REPORT NAME
    // ============================================================

    reportName: {
      type: String,
      trim: true,
      default: "",
    },

    // ============================================================
    // DATE RANGE
    // ============================================================

    startDate: {
      type: Date,
      required: true,
    },

    endDate: {
      type: Date,
      required: true,
    },

    // ============================================================
    // SALES REPORT
    // ============================================================

    totalOrders: {
      type: Number,
      default: 0,
    },

    totalRevenue: {
      type: Number,
      default: 0,
    },

    totalDiscount: {
      type: Number,
      default: 0,
    },

    totalTax: {
      type: Number,
      default: 0,
    },

    totalShipping: {
      type: Number,
      default: 0,
    },

    totalQuantitySold: {
      type: Number,
      default: 0,
    },

    averageOrderValue: {
      type: Number,
      default: 0,
    },

    cancelledOrders: {
      type: Number,
      default: 0,
    },

    refundedAmount: {
      type: Number,
      default: 0,
    },

    // ============================================================
    // CUSTOMER REPORT
    // ============================================================

    totalCustomers: {
      type: Number,
      default: 0,
    },

    newCustomers: {
      type: Number,
      default: 0,
    },

    activeCustomers: {
      type: Number,
      default: 0,
    },

    inactiveCustomers: {
      type: Number,
      default: 0,
    },

    // ============================================================
    // DAILY SALES
    // ============================================================

    dailySales: [
      {
        date: {
          type: Date,
        },

        orders: {
          type: Number,
          default: 0,
        },

        revenue: {
          type: Number,
          default: 0,
        },
      },
    ],

    // ============================================================
    // ORDER STATUS
    // ============================================================

    orderStatuses: [
      {
        status: {
          type: String,
        },

        count: {
          type: Number,
          default: 0,
        },

        amount: {
          type: Number,
          default: 0,
        },
      },
    ],

    // ============================================================
    // PAYMENT STATUS
    // ============================================================

    paymentStatuses: [
      {
        status: {
          type: String,
        },

        count: {
          type: Number,
          default: 0,
        },

        amount: {
          type: Number,
          default: 0,
        },
      },
    ],

    // ============================================================
    // GENERATED BY
    // ============================================================

    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// ============================================================
// INDEX
// ============================================================

reportSchema.index({
  reportType: 1,
  startDate: 1,
  endDate: 1,
});

// ============================================================
// EXPORT
// ============================================================

module.exports =
  mongoose.models.Report ||
  mongoose.model("Report", reportSchema);